# Generated by Django 4.2.4 on 2023-11-04 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model_code', models.CharField(max_length=50)),
                ('ref_num', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50)),
                ('engine_size', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('engine_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic transmission'), ('manual', 'Manual Transmission')], max_length=10, null=True)),
                ('steering', models.CharField(blank=True, choices=[('left', 'american cars'), ('right', 'normal cars')], max_length=10, null=True)),
                ('fuel', models.CharField(blank=True, choices=[('diesel', 'diesel oil'), ('petrol', 'petrol oil')], max_length=10, null=True)),
                ('ext_color', models.CharField(blank=True, max_length=20, null=True)),
                ('seats', models.IntegerField(default=4)),
                ('doors', models.IntegerField(default=4)),
                ('m3', models.FloatField(blank=True, null=True)),
                ('dimension_height', models.FloatField(blank=True, null=True)),
                ('dimension_width', models.FloatField(blank=True, null=True)),
                ('dimension_lenght', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('max_cap', models.FloatField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
